In [34]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

In [35]:
# draw a graph between cities and color by PageRank
pairs1 = pd.read_csv('/home/hee3be/Dev/data-science/Untitled Folder/networkx_city_pairs.csv', names=['city1', 'city2'])
pairs2 = pd.read_csv('/home/hee3be/Dev/data-science/Untitled Folder/networkx_city_pairs.csv', names=['city2', 'city1'])
pairs = pd.concat([pairs1, pairs2])

In [36]:
# create adjacency matrix
adjacency = pd.crosstab(pairs['city1'], pairs['city2'])
adjacency

city2,42,Atlanta,Atlantyda,Buenos Aires,Chicago,Darwin,Denver,Frankfurt,Ibiza,Istanbul,...,Lagos,London,Los Angeles,Moscow,New York,Paris,San Francisco,Sao Paulo,Tripolis,Washington
city1,,,,,,,,,,,,,,,,,,,,,
42,0,0,1,0,0,1,0,0,1,0,...,0,1,0,0,1,0,0,1,0,0
Atlanta,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Atlantyda,1,0,0,0,0,1,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
Buenos Aires,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Chicago,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Darwin,1,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
Denver,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Frankfurt,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,1,0,0,0,0
Ibiza,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
Istanbul,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
Jacksonville,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
Kairo,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
Lagos,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
London,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Los Angeles,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Moscow,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
New York,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Paris,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
San Francisco,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Sao Paulo,1,0,1,1,0,1,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
Tripolis,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Washington,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [37]:
# create graph object with NetworkX library
g = nx.from_pandas_adjacency(adjacency)
g

In [38]:
# run PageRank algorithm and add result to matrix
rank = nx.pagerank(g, alpha=0.85)
adjacency['rank'] = pd.Series(rank)

In [39]:
adjacency = adjacency.sort_values(by='rank', ascending=False)
print(adjacency)

city2          42  Atlanta  Atlantyda  Buenos Aires  Chicago  Darwin  Denver  \
city1
Ibiza           1        0          1             0        0       1       0
Sao Paulo       1        0          1             1        0       1       0
42              0        0          1             0        0       1       0
Atlantyda       1        0          0             0        0       1       0
Darwin          1        0          1             0        0       0       0
Jacksonville    0        1          1             0        0       0       0
Frankfurt       0        0          0             0        0       0       0
Chicago         0        0          0             0        0       0       1
Istanbul        0        0          0             0        0       0       0
Washington      0        0          0             0        1       0       0
New York        1        0          0             0        0       0       0
Paris           0        0          0             0        0       0       0
Denver          0        1          0             0        1       0       0
San Francisco   0        0          0             0        1       0       0
Kairo           0        0          0             0        0       0       0
Atlanta         0        0          0             0        0       0       1
London          1        0          0             0        0       0       0
Los Angeles     0        0          0             0        0       1       0
Tripolis        0        0          0             0        0       0       0
Lagos           0        0          1             0        0       0       0
Moscow          0        0          0             0        0       0       0
Buenos Aires    0        0          0             0        0       0       0

city2          Frankfurt  Ibiza  Istanbul  ...  London  Los Angeles  Moscow  \
city1                                      ...
Ibiza                  0      0         1  ...       0            0       0
Sao Paulo              0      1         0  ...       0            0       0
42                     0      1         0  ...       1            0       0
Atlantyda              0      1         0  ...       0            0       0
Darwin                 0      1         0  ...       0            1       0
Jacksonville           0      0         0  ...       0            0       0
Frankfurt              0      0         1  ...       0            0       1
Chicago                0      0         0  ...       0            0       0
Istanbul               1      1         0  ...       0            0       0
Washington             0      0         0  ...       0            0       0
New York               0      0         0  ...       0            0       0
Paris                  1      0         0  ...       1            0       0
Denver                 0      0         0  ...       0            0       0
San Francisco          0      0         0  ...       0            1       0
Kairo                  0      0         1  ...       0            0       0
Atlanta                0      0         0  ...       0            0       0
London                 0      0         0  ...       0            0       0
Los Angeles            0      0         0  ...       0            0       0
Tripolis               0      1         0  ...       0            0       0
Lagos                  0      0         0  ...       0            0       0
Moscow                 1      0         0  ...       0            0       0
Buenos Aires           0      0         0  ...       0            0       0

city2          New York  Paris  San Francisco  Sao Paulo  Tripolis  \
city1
Ibiza                 0      0              0          1         1
Sao Paulo             0      0              0          0         0
42                    1      0              0          1         0
Atlantyda             0      0              0          1         0
Darwin                0      0              0          1         0
Jacksonville          1      0              0          0         0
Frankfurt             0      1              0          0         0
Chicago               0      0              1          0         0
Istanbul              0      0              0          0         0
Washington            1      0              0          0         0
New York              0      0              0          0         0
Paris                 0      0              0          0         0
Denver                0      0              0          0         0
San Francisco         0      0              0          0         0
Kairo                 0      0              0          0         1
Atlanta               0      0              0          0         0
London                0      1              0          0         0
Los Angeles           0      0              1          0         0
Tripolis              0      0              0          0         0
Lagos                 0      0              0          1         0
Moscow                0      0              0          0         0
Buenos Aires          0      0              0          1         0

city2          Washington      rank
city1
Ibiza                   0  0.076894
Sao Paulo               0  0.076751
42                      0  0.075830
Atlantyda               0  0.074027
Darwin                  0  0.063508
Jacksonville            1  0.056132
Frankfurt               0  0.054771
Chicago                 1  0.048895
Istanbul                0  0.047676
Washington              0  0.044530
New York                1  0.042106
Paris                   0  0.036368
Denver                  0  0.034952
San Francisco           0  0.034365
Kairo                   0  0.033995
Atlanta                 0  0.033601
London                  0  0.033018
Los Angeles             0  0.032220
Tripolis                0  0.032158
Lagos                   0  0.028178
Moscow                  0  0.022335
Buenos Aires            0  0.017691

[22 rows x 23 columns]

In [40]:
adjacency.columns

Index(['42', 'Atlanta', 'Atlantyda', 'Buenos Aires', 'Chicago', 'Darwin',
       'Denver', 'Frankfurt', 'Ibiza', 'Istanbul', 'Jacksonville', 'Kairo',
       'Lagos', 'London', 'Los Angeles', 'Moscow', 'New York', 'Paris',
       'San Francisco', 'Sao Paulo', 'Tripolis', 'Washington', 'rank'],
      dtype='object', name='city2')

In [41]:
adjacency.index

Index(['Ibiza', 'Sao Paulo', '42', 'Atlantyda', 'Darwin', 'Jacksonville',
       'Frankfurt', 'Chicago', 'Istanbul', 'Washington', 'New York', 'Paris',
       'Denver', 'San Francisco', 'Kairo', 'Atlanta', 'London', 'Los Angeles',
       'Tripolis', 'Lagos', 'Moscow', 'Buenos Aires'],
      dtype='object', name='city1')

In [42]:
# color by city state
cities = pd.read_csv('/home/hee3be/Dev/data-science/Untitled Folder/networkx_city_pairs.csv', names=['state'], index_col=0)
cities

                      state
42                Atlantyda
42                   Darwin
42                    Ibiza
42                   London
42                Sao Paulo
42                 New York
Atlanta              Denver
Atlanta        Jacksonville
Atlantyda            Darwin
Atlantyda             Lagos
Atlantyda         Sao Paulo
Atlantyda      Jacksonville
Atlantyda             Ibiza
Buenos Aires      Sao Paulo
Chicago       San Francisco
Chicago          Washington
Darwin                Ibiza
Darwin          Los Angeles
Darwin            Sao Paulo
Denver              Chicago
Frankfurt          Istanbul
Frankfurt             Paris
Frankfurt            Moscow
Ibiza              Istanbul
Ibiza              Tripolis
Ibiza             Sao Paulo
Istanbul              Kairo
Jacksonville       New York
Jacksonville     Washington
Kairo              Tripolis
Lagos             Sao Paulo
London                Paris
Los Angeles   San Francisco
New York         Washington

In [43]:
col = {'safe': 0.0, 'live': 0.5, 'dead': 1.0}
cities['color'] = cities['state'].apply(col.get)
colors = [cities.loc[city]['color'] for city in g.nodes()]
plt.figure()
nx.draw(g, node_color=colors, labels=dict(zip(g.nodes(), g.nodes())))

KeyError: 'Moscow'

In [44]:
plt.show()